---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./media/overlays/dev
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: homelab-apps
  targetNamespace: media
  timeout: 2m0s
  wait: true
