---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 3m0s
  ref:
    branch: main
  url: ssh://git@github.com/romaincrlt/homelab-apps
