---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 3h
  path: ./test
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
  targetNamespace: test
  timeout: 2m0s
  wait: true
