---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  interval: 3h
  retryInterval: 10m
  path: ./media/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
  targetNamespace: media
  timeout: 2m0s
  wait: true
